import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { FinalCta, PageIntro } from "@/components/invite-parts";
import { templates } from "@/lib/invites";

const liveInviteUrls = {
  Editorial: "https://eviake.tracey-munyagia.workers.dev/invite/brian-otieno",
  Romance: "https://eviake.tracey-munyagia.workers.dev/invite/kellie-and-martin-s-wedding",
  Celebration: "https://eviake.tracey-munyagia.workers.dev/invite/got-game-night",
} as const;

export const Route = createFileRoute("/templates")({ head: () => ({ meta: [
  { title: "Invitation Templates — Evia Invites" }, { name: "description", content: "Explore Editorial, Romance and Celebration invitation templates, each personalized for your event." }, { property: "og:title", content: "Invitation Templates — Evia Invites" }, { property: "og:description", content: "Three beautifully considered starting points for your digital invitation." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Templates });
function Templates() { return <><PageIntro kicker="THE COLLECTION" title="Find the feeling. We'll make it yours." text="A carefully curated starting point for the invitation you'll be proud to share."/><section className="py-18 md:py-24"><div className="section-shell space-y-20 md:space-y-28">{templates.map((template, index) => <article id={template.name.toLowerCase()} key={template.name} className="grid scroll-mt-28 items-center gap-10 md:grid-cols-2 md:gap-16"><div className={`relative aspect-[4/5] max-h-[650px] overflow-hidden bg-primary ${index % 2 ? "md:order-2" : ""}`}><iframe src={liveInviteUrls[template.name]} title={`${template.name} live invitation preview`} loading="lazy" allow="autoplay 'none'; microphone 'none'; camera 'none'" className="pointer-events-none h-full w-full border-0 bg-white"/><div className="absolute inset-x-4 bottom-4 flex justify-center"><a href={liveInviteUrls[template.name]} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground shadow-lg transition-colors hover:bg-primary/90">Open live invite <ExternalLink className="size-3.5" /></a></div></div><div><p className="eyebrow">0{index + 1} / 03 · MASTER TEMPLATE</p><h2 className="mt-5 font-display text-5xl text-primary md:text-6xl">{template.name}</h2><p className="mt-3 text-lg text-muted-foreground">{template.descriptor}</p><div className="my-8 h-px bg-border"/><p className="editorial-label text-muted-foreground">SUITABLE FOR</p><p className="mt-3 text-base leading-7">{template.events}</p><p className="editorial-label mt-8 text-muted-foreground">FEATURES</p><ul className="mt-4 space-y-3">{template.features.map(feature => <li key={feature} className="flex items-center gap-3 text-sm"><Check className="size-4 text-gold"/>{feature}</li>)}</ul><div className="mt-10 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/create" search={{ template: template.name }}>Choose {template.name} <ArrowRight /></Link></Button><a href={liveInviteUrls[template.name]} target="_blank" rel="noreferrer" className="inline-flex h-11 items-center gap-2 border border-border px-5 text-sm font-semibold text-primary transition-colors hover:border-primary">View invite <ExternalLink className="size-4" /></a></div></div></article>)}</div></section><FinalCta /></> }
